networks:
  homelab_macvlan:
    name: homelab-macvlan
    external: true

services:
  pihole:
    container_name: pihole-${ENV_NAME}
    image: pihole/pihole:${PIHOLE_VERSION}
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
      FTLCONF_local_ipv4: '${PIHOLE_IP}'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_misc_etc_dnsmasq_d: 'true'  # Required for migration from v5
    volumes:
      - '/srv/data/${ENV_NAME}/pihole/etc/pihole:/etc/pihole'
      - '/srv/data/${ENV_NAME}/pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN  # Required for Pi-hole to function properly
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      homelab_macvlan:
        ipv4_address: ${PIHOLE_IP}

  jellyfin:
    container_name: jellyfin-${ENV_NAME}
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    volumes:
      - /tmp/var/${ENV_NAME}/jellyfin/cache:/cache
      - /srv/data/${ENV_NAME}/jellyfin/config:/config
      - /srv/data/${ENV_NAME}/jellyfin/Music:/Music
      - /srv/data/${ENV_NAME}/jellyfin/Movies:/Movies
      - /srv/data/${ENV_NAME}/jellyfin/ChildrensMovies:/ChildrensMovies
    tmpfs:
      - /tmp/jellyfin
    restart: 'unless-stopped'
    networks:
      homelab_macvlan:
        ipv4_address: ${JELLYFIN_IP}

  hello-world:
    container_name: hello-world-${ENV_NAME}
    image: nginx:${HELLO_WORLD_VERSION}
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - /srv/data/${ENV_NAME}/hello-world:/usr/share/nginx/html:ro
    networks:
      homelab_macvlan:
        ipv4_address: ${HELLO_WORLD_IP}
