networks:
  homelab-macvlan:
    external: true

services:
  pihole:
    image: pihole/pihole:${PIHOLE_VERSION}
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
      FTLCONF_local_ipv4: '${PIHOLE_IP}'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_misc_etc_dnsmasq_d: 'true'
      PIHOLE_UID: '${UID}'
      PIHOLE_GID: '${GID}'
    volumes:
      - '/srv/data/${ENV_NAME}/pihole/etc/pihole:/etc/pihole'
      - '/srv/data/${ENV_NAME}/pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      homelab-macvlan:
        ipv4_address: ${PIHOLE_IP}
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.hardware == rpi-3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    user: '${UID}:${GID}'
    volumes:
      - /tmp/var/${ENV_NAME}/jellyfin/cache:/cache
      - /tmp/var/${ENV_NAME}/jellyfin/tmp:/tmp/jellyfin
      - /srv/data/${ENV_NAME}/jellyfin/config:/config
      - /srv/data/${ENV_NAME}/jellyfin/Music:/Music
      - /srv/data/${ENV_NAME}/jellyfin/Movies:/Movies
      - /srv/data/${ENV_NAME}/jellyfin/ChildrensMovies:/ChildrensMovies
    networks:
      homelab-macvlan:
        ipv4_address: ${JELLYFIN_IP}
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.hardware == n100
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  hello-world:
    image: nginx:${HELLO_WORLD_VERSION}
    user: '${UID}:${GID}'
    volumes:
      - /srv/data/${ENV_NAME}/hello-world:/usr/share/nginx/html:ro
    networks:
      homelab-macvlan:
        ipv4_address: ${HELLO_WORLD_IP}
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M