networks:
  homelab_macvlan:
    name: homelab-macvlan
    external: true

services:
  pihole:
    container_name: pihole-${ENV_NAME}
    image: pihole/pihole:${PIHOLE_VERSION}
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
      FTLCONF_local_ipv4: '${PIHOLE_IP}'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_misc_etc_dnsmasq_d: 'true'  # Required for migration from v5
    volumes:
      - './pihole/${ENV_NAME}/etc-pihole:/etc/pihole'
      - './pihole/${ENV_NAME}/etc-dnsmasq.d:/etc/dnsmasq.d'
      - './dns/${ENV_NAME}/custom-dns.conf:/etc/dnsmasq.d/02-custom-dns.conf'
    cap_add:
      - NET_ADMIN  # Required for Pi-hole to function properly
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      homelab_macvlan:
        ipv4_address: ${PIHOLE_IP}

  jellyfin:
    container_name: jellyfin-${ENV_NAME}
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    volumes:
      - ./jellyfin/${ENV_NAME}/config:/config
      - ./jellyfin/${ENV_NAME}/cache:/cache
      - ./jellyfin/${ENV_NAME}/tmp:/tmp/jellyfin
      - /media/Data-0/${ENV_NAME}/jellyfin/Music:/Music
      - /media/Data-0/${ENV_NAME}/jellyfin/Movies:/Movies
      - /media/Data-0/${ENV_NAME}/jellyfin/ChildrensMovies:/ChildrensMovies
    restart: 'unless-stopped'
    networks:
      homelab_macvlan:
        ipv4_address: ${JELLYFIN_IP}

  hello-world:
    container_name: hello-world-${ENV_NAME}
    image: nginx:${HELLO_WORLD_VERSION}
    restart: unless-stopped
    volumes:
      - ./hello-world/${ENV_NAME}:/usr/share/nginx/html:ro
    networks:
      homelab_macvlan:
        ipv4_address: ${HELLO_WORLD_IP}
