networks:
  local_network:
    driver: bridge

  homelab_macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.192/26

services:
  nginx:
    restart: unless-stopped
    container_name: nginx-${ENV_NAME}
    image: nginx:${NGINX_VERSION}
    ports:
      - "443:443"  # HTTPS port
      - "80:80"    # HTTP port
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - pihole
      - jellyfin
    networks:
      - local_network
  pihole:
    container_name: pihole-${ENV_NAME}
    image: pihole/pihole:${PIHOLE_VERSION}
    ports:
      - "53:53/tcp"
      - "53:53/udp" 
      - "81:80/tcp"  # Expose Pi-hole web interface on port 81
    environment:
      TZ: 'Europe/London'
      FTLCONF_local_ipv4: '192.168.1.204'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_misc_etc_dnsmasq_d: 'true'  # Required for migration from v5
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - './custom-dns.conf:/etc/dnsmasq.d/02-custom-dns.conf'
    cap_add:
      - NET_ADMIN  # Required for Pi-hole to function properly
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - local_network

  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    container_name: jellyfin-${ENV_NAME}
    network_mode: host
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./jellyfin/tmp:/tmp/jellyfin
      - type: bind
        source: /media/pi/Media/Music
        target: /Music
      - type: bind
        source: /media/pi/Media/Movies
        target: /Movies
      - type: bind
        source: /media/pi/Media/Books
        target: /Books
      - type: bind
        source: /media/pi/Media/ChildrensMovies
        target: /ChildrensMovies
      - type: bind
        source: /media/pi/Media/Audiobooks
        target: /Audiobooks
    restart: 'unless-stopped'
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  hello-world:
    image: nginx:${HELLO_WORLD_VERSION}
    container_name: hello-world-${ENV_NAME}
    restart: unless-stopped
    volumes:
      - ./hello-world:/usr/share/nginx/html:ro
    networks:
      homelab_macvlan:
        ipv4_address: ${HELLO_WORLD_IP}
