networks:
  homelab-overlay:
    driver: overlay
    attachable: true

services:
  pihole:
    container_name: pihole-${ENV_NAME}
    image: pihole/pihole:${PIHOLE_VERSION}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN_SUFFIX}`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_misc_etc_dnsmasq_d: 'true'
    volumes:
      - '/srv/data/${ENV_NAME}/pihole/etc/pihole:/etc/pihole'
      - '/srv/data/${ENV_NAME}/pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
      - './dns/custom-dns.conf:/etc/dnsmasq.d/02-custom-dns.conf'
    ports:
      - "${PIHOLE_DNS_PORT}:53/tcp"
      - "${PIHOLE_DNS_PORT}:53/udp"
    cap_add:
      - NET_ADMIN  # Required for Pi-hole to function properly
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - homelab-overlay

  jellyfin:
    container_name: jellyfin-${ENV_NAME}
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_SUFFIX}`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    ports:
      - "${JELLYFIN_HTTP_PORT}:8096"
      - "${JELLYFIN_HTTPS_PORT}:8920"
      - "${JELLYFIN_DLNA_PORT}:1900/udp"
      - "${JELLYFIN_DISCOVERY_PORT}:7359/udp"
    volumes:
      - /tmp/var/${ENV_NAME}/jellyfin/cache:/cache
      - /srv/data/${ENV_NAME}/jellyfin/config:/config
      - /srv/data/${ENV_NAME}/jellyfin/Music:/Music
      - /srv/data/${ENV_NAME}/jellyfin/Movies:/Movies
      - /srv/data/${ENV_NAME}/jellyfin/ChildrensMovies:/ChildrensMovies
    tmpfs:
      - /tmp/jellyfin
    restart: 'unless-stopped'
    networks:
      - homelab-overlay

  hello-world:
    container_name: hello-world-${ENV_NAME}
    image: nginx:${HELLO_WORLD_VERSION}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello-world.rule=Host(`hello-world.${DOMAIN_SUFFIX}`)"
      - "traefik.http.services.hello-world.loadbalancer.server.port=80"
    restart: unless-stopped
    volumes:
      - /srv/data/${ENV_NAME}/hello-world:/usr/share/nginx/html:ro
    networks:
      - homelab-overlay

  traefik:
    container_name: traefik-${ENV_NAME}
    image: traefik:${TRAEFIK_VERSION}
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_HTTPS_PORT}:443"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - homelab-overlay
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
