services:
  ser2net:
    build:
      context: .
    image: homelab/ser2net:local
    container_name: ser2net-${ENV_NAME}
    restart: unless-stopped
    devices:
      - ${SER2NET_DEVICE}:/dev/ttyUSB0
    volumes:
      - ./ser2net.yaml:/etc/ser2net/ser2net.yaml:ro
    ports:
      - "${SER2NET_TCP_PORT}:3333"
    mem_limit: 32m
