global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.home:9090']

  - job_name: 'node'
    static_configs:
      - targets: 
          - '192.168.1.204:9100'
          - '192.168.1.11:9100'
    relabel_configs:
      - source_labels: [__address__]
        regex: '192\.168\.1\.204:.*'
        target_label: node_name
        replacement: 'rpi-3-0'
      - source_labels: [__address__]
        regex: '192\.168\.1\.11:.*'
        target_label: node_name
        replacement: 'geekom-mini-air12-0'
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: instance
        replacement: '${1}'

  - job_name: 'cadvisor'
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080

  - job_name: 'traefik'
    dns_sd_configs:
      - names:
          - 'tasks.traefik'
        type: 'A'
        port: 8080
    metrics_path: '/metrics'

  - job_name: 'docker-swarm'
    static_configs:
      - targets: ['dockerd-exporter:9323']